### ISSUE TITLE
Do you find the name of this package confusing?

### ISSUE THREAD

**Issue by hectormenendez** [gikmx/npm#6]
It has come to my attention that [some people find this name confusing](https://www.reddit.com/r/javascript/comments/7b3kni/the_company_i_work_for_just_opensourced_all_its/dpfwqlw/), since it appears to be a fork or even a new version of _npm_.
Do you have any suggestions for a new name that fits better the scope of this package? 

so far I have received these suggestions:

- `@gik/npm-scripts`
- `@gik/npms`

**Comment by polarbearwithme** [comment]
npms is good
